CREATE USER flyway WITH PASSWORD 'flyway' CREATEROLE;
CREATE USER airflow WITH PASSWORD 'airflow';
CREATE DATABASE airflow;
GRANT CONNECT ON DATABASE airflow TO airflow;
GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;